# (C) Copyright 2015
# Purna Chandra Mandal, purna.mandal@microchip.com.
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y = cpu.o reset.o lowlevel_init.o
ifndef CONFIG_SYS_NO_FLASH
obj-y += flash.o
endif